name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        arch: [ x64 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/CiaranOMara/PublicJuliaRegistry.jl"))'
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
        env:
          JULIA_NUM_THREADS: "3"
      - name: Create CodeCov
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
